"""init db

Revision ID: 3b517b095604
Revises: 
Create Date: 2024-02-04 01:12:04.544403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b517b095604'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=30), nullable=False),
    sa.Column('e_mail', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('access_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('e_mail'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('threads',
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('branch_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], name='user_threads'),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_table('branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], name='user_branches'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], name='thread_branches'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('into_branch_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='branch_posts'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], name='user_posts'),
    sa.PrimaryKeyConstraint('branch_id', 'into_branch_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('branches')
    op.drop_table('threads')
    op.drop_table('users')
    # ### end Alembic commands ###
