"""empty message

Revision ID: 685f38e60562
Revises: 4f68bedf6e9c
Create Date: 2024-02-04 05:51:53.193329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685f38e60562'
down_revision = '4f68bedf6e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('u_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('u_id')

    # ### end Alembic commands ###
