"""empty message

Revision ID: 8fe1835d1a7c
Revises: 685f38e60562
Create Date: 2024-02-04 05:59:47.774052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe1835d1a7c'
down_revision = '685f38e60562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('into_branch_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('into_branch_id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
