"""empty message

Revision ID: a67bcb1a20a7
Revises: 8fe1835d1a7c
Create Date: 2024-02-04 06:00:02.794976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67bcb1a20a7'
down_revision = '8fe1835d1a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('into_branch_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('into_branch_id')

    # ### end Alembic commands ###
