"""empty message

Revision ID: b5ac498c360e
Revises: dec4e4ca3821
Create Date: 2024-02-11 04:08:24.967063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ac498c360e'
down_revision = 'dec4e4ca3821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=30), nullable=False))
        batch_op.drop_constraint('users_e_mail_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('e_mail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('e_mail', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('users_e_mail_key', ['e_mail'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###
