"""empty message

Revision ID: dec4e4ca3821
Revises: c6fa52da667f
Create Date: 2024-02-04 06:05:30.753806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec4e4ca3821'
down_revision = 'c6fa52da667f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('into_branch_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('into_branch_id')

    # ### end Alembic commands ###
